// Action Types
export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const UNAUTH_USER_REQUEST = 'UNAUTH_USER_REQUEST';
export const UNAUTH_USER_SUCCESS = 'UNAUTH_USER_SUCCESS';
export const UNAUTH_USER_FAILURE = 'UNAUTH_USER_FAILURE';
