export const GET_CONFIGURATIONS_REQUEST = 'GET_CONFIGURATIONS_REQUEST';
export const GET_CONFIGURATIONS_SUCCESS = 'GET_CONFIGURATIONS_SUCCESS';
export const GET_CONFIGURATIONS_FAILURE = 'GET_CONFIGURATIONS_FAILURE';

export const SAVE_CONFIGURATION_REQUEST = 'SAVE_CONFIGURATION_REQUEST';
export const SAVE_CONFIGURATION_SUCCESS = 'SAVE_CONFIGURATION_SUCCESS';
export const SAVE_CONFIGURATION_FAILURE = 'SAVE_CONFIGURATION_FAILURE';

export const DELETE_CONFIGURATION_REQUEST = 'DELETE_CONFIGURATION_REQUEST';
export const DELETE_CONFIGURATION_SUCCESS = 'DELETE_CONFIGURATION_SUCCESS';
export const DELETE_CONFIGURATION_FAILURE = 'DELETE_CONFIGURATION_FAILURE';

export const CLEAR_CONFIGURATION_MESSAGE = 'CLEAR_CONFIGURATION_MESSAGE';
